language: php

php:
  - 5.6

notifications:
  email:
    - viniciuslcpereira@gmail.com
    - wilder_roberto@hotmail.com

before_script:
  - cp .env.example .env
  - composer install

script:
  - vendor/bin/phpunit