language: php

php:
  - 7.0

notifications:
  email:
    on_success: always
    recipients:
      - viniciuslcpereira@gmail.com

before_script:
  - cp .env.example .env
  - composer install
  - php artisan key:generate
  - php artisan serve &

script:
  - vendor/bin/phpunit