language: php

php:
  - 7.0

sudo: true

notifications:
  email:
    on_success: always
    recipients:
      - viniciuslcpereira@gmail.com

before_script:
  - cp .env.example .env
  - composer install
  - php artisan key:generate
  - php artisan serve &
  - bash .travis.install-mysql-5.7.sh
  - mysql -e "CREATE DATABASE IF NOT EXISTS fiscaluno"
  - php artisan migrate
  - php artisan db:seed

script:
  - vendor/bin/phpunit